---
- hosts: localhost
  name: "Setup da Demo do Istio no Openshift"
  connection: local
  vars:
    ocp_url: apps.brasilia1.openshiftworkshop.com

  tasks:


    - name: Projeto istio-system
      shell: oc project istio-system

    - name: Criando kiali config-map
      shell: curl https://raw.githubusercontent.com/kiali/kiali/v0.7.2/deploy/openshift/kiali-configmap.yaml | VERSION_LABEL=v0.7.2 JAEGER_URL=https://jaeger-query-istio-system.{{ ocp_url }} GRAFANA_URL=https://grafana-istio-system.{{ ocp_url }} envsubst | oc create -n istio-system -f -

    - name: Criando kiali secrets
      shell: curl https://raw.githubusercontent.com/kiali/kiali/v0.7.2/deploy/openshift/kiali-secrets.yaml | VERSION_LABEL=v0.7.2 envsubst | oc create -n istio-system -f -

    - name: Criando kiali
      shell: "curl https://raw.githubusercontent.com/kiali/kiali/v0.7.2/deploy/openshift/kiali.yaml | VERSION_LABEL=v0.7.2 IMAGE_NAME=kiali/kiali IMAGE_VERSION=v0.7.2 NAMESPACE=istio-system VERBOSE_MODE=4 IMAGE_PULL_POLICY_TOKEN='imagePullPolicy: Always' envsubst | oc create -n istio-system -f - "

